ISerialPort.h: fix missing include
Fixes #30 on GitHub:

bullycpp/ISerialPort.h:32:41: error: ‘string’ in namespace ‘std’ does not name a type
   32 |         virtual void setName(const std::string&) = 0;
      |                                         ^~~~~~
bullycpp/ISerialPort.h:21:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?